# TCL File Generated by Component Editor 12.0
# Wed May 23 11:24:27 PDT 2012
# DO NOT MODIFY


# 
# frequency_counter "frequency_counter" v1.0
# null 2012.05.23.11:24:27
# Find out target frequency by using system clock
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module frequency_counter
# 
set_module_property DESCRIPTION "Find out target frequency by using system clock"
set_module_property NAME frequency_counter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP BoardTestSystem
set_module_property DISPLAY_NAME frequency_counter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL frequency_counter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file frequency_counter.v VERILOG PATH frequency_counter.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL frequency_counter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file frequency_counter.v VERILOG PATH frequency_counter.v


# 
# parameters
# 
add_parameter SYSTEM_CLK_FREQ_PICO_SEC INTEGER 20000 "This is the clk that you've already known the frequency to sample target"
set_parameter_property SYSTEM_CLK_FREQ_PICO_SEC DEFAULT_VALUE 20000
set_parameter_property SYSTEM_CLK_FREQ_PICO_SEC DISPLAY_NAME "SYSTEM CLK frequency in pico seconds"
set_parameter_property SYSTEM_CLK_FREQ_PICO_SEC WIDTH ""
set_parameter_property SYSTEM_CLK_FREQ_PICO_SEC TYPE INTEGER
set_parameter_property SYSTEM_CLK_FREQ_PICO_SEC UNITS None
set_parameter_property SYSTEM_CLK_FREQ_PICO_SEC HDL_PARAMETER true
set_parameter_property SYSTEM_CLK_FREQ_PICO_SEC ALLOWED_RANGES 1:2147483647
set_parameter_property SYSTEM_CLK_FREQ_PICO_SEC DESCRIPTION "This is the clk that you've already known the frequency to sample target"


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressAlignment DYNAMIC
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr isMemoryDevice false
set_interface_property csr isNonVolatileStorage false
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr printableDevice false
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true

add_interface_port csr csr_address address Input 4
add_interface_port csr csr_read read Input 1
add_interface_port csr csr_readdata readdata Output 32
add_interface_port csr csr_waitrequest waitrequest Output 1


# 
# connection point sample_clk
# 
add_interface sample_clk clock end
set_interface_property sample_clk clockRate 0
set_interface_property sample_clk ENABLED true

add_interface_port sample_clk sample_clk clk Input 1


# 
# connection point sample_reset_n
# 
add_interface sample_reset_n reset end
set_interface_property sample_reset_n associatedClock sample_clk
set_interface_property sample_reset_n synchronousEdges DEASSERT
set_interface_property sample_reset_n ENABLED true

add_interface_port sample_reset_n sample_reset_n reset_n Input 1

