# TCL File Generated by Component Editor 12.0
# Tue May 22 10:07:04 PDT 2012
# DO NOT MODIFY


# 
# status_mon "status_mon" v1.0
# null 2012.05.22.10:07:04
# EMIF status monitor
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module status_mon
# 
set_module_property DESCRIPTION "EMIF status monitor"
set_module_property NAME status_mon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP BoardTestSystem
set_module_property DISPLAY_NAME status_mon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL status_mon
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file status_mon.v VERILOG PATH status_mon.v

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog TOP_LEVEL status_mon
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file status_mon.v VERILOG PATH status_mon.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point slv
# 
add_interface slv avalon end
set_interface_property slv addressAlignment DYNAMIC
set_interface_property slv addressUnits WORDS
set_interface_property slv associatedClock clock
set_interface_property slv associatedReset reset_n
set_interface_property slv burstOnBurstBoundariesOnly false
set_interface_property slv explicitAddressSpan 0
set_interface_property slv holdTime 0
set_interface_property slv isMemoryDevice false
set_interface_property slv isNonVolatileStorage false
set_interface_property slv linewrapBursts false
set_interface_property slv maximumPendingReadTransactions 0
set_interface_property slv printableDevice false
set_interface_property slv readLatency 0
set_interface_property slv readWaitTime 1
set_interface_property slv setupTime 0
set_interface_property slv timingUnits Cycles
set_interface_property slv writeWaitTime 0
set_interface_property slv ENABLED true

add_interface_port slv slv_read_n read_n Input 1
add_interface_port slv slv_write_n write_n Input 1
add_interface_port slv slv_address address Input 2
add_interface_port slv slv_cs_n chipselect_n Input 1
add_interface_port slv slv_data_write writedata Input 32
add_interface_port slv slv_data_read readdata Output 32


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end cal_fail_mon export Output 1
add_interface_port conduit_end cal_success_mon export Output 1
add_interface_port conduit_end init_done_mon export Output 1


# 
# connection point reset_source
# 
add_interface reset_source reset start
set_interface_property reset_source associatedClock clock
set_interface_property reset_source associatedDirectReset ""
set_interface_property reset_source associatedResetSinks ""
set_interface_property reset_source synchronousEdges DEASSERT
set_interface_property reset_source ENABLED true

add_interface_port reset_source reset_out_n reset_n Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock slv_clk clk Input 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true

add_interface_port reset_n slv_reset_n reset_n Input 1


# 
# connection point status
# 
add_interface status conduit end
set_interface_property status associatedClock ""
set_interface_property status associatedReset ""
set_interface_property status ENABLED true

add_interface_port status local_init_done local_init_done Input 1
add_interface_port status local_cal_success local_cal_success Input 1
add_interface_port status local_cal_fail local_cal_fail Input 1

