#!/bin/bash
#
# This script creates the application_selector application in this directory.

# First, check to see if $SOPC_KIT_NIOS2 environmental variable is set.
# This variable is required for the command line tools to execute correctly.
if [ -z $SOPC_KIT_NIOS2 ]
then
    echo Required \$SOPC_KIT_NIOS2 Environmental Variable is not set!
    exit 1
fi

# Also make sure that the APP has not been created already.  Check for
# existence of Makefile in the app directory
if [ -f ./Makefile ]
then
    echo Application has already been created!  Delete Makefile if you want to create a new application makefile
    exit 1
fi

BSP_NAME=ucosii_net_rozipfs
BSP_DIR=../../bsp/ucosii_net_rozipfs

#always run $BSP_DIR/create-this-bsp
pushd $BSP_DIR >> /dev/null
./create-this-bsp "$@" || {
	echo "create-this-bsp failed"
	exit 1
}
popd >> /dev/null

cmd="nios2-app-generate-makefile --bsp-dir $BSP_DIR --src-rdir ./src --elf-name web_server.elf --set APP_CFLAGS_OPTIMIZATION -O0 --set APP_INCLUDE_DIRS \"src/flash_intel_p30 src/srec\""

echo "create-this-app: Running \"$cmd\""
$cmd || {
    echo "nios2-app-generate-makefile failed"
    exit 1
}

cmd="make"

echo "create-this-app: Running \"$cmd\""
$cmd || {
    echo "make failed"
    exit 1
}


echo
echo "To download and run the application:"
echo "    1. Make sure the board is connected to the system."
echo "    2. Run 'nios2-configure-sof -C ../../..' to configure the FPGA with the hardware design."
echo "    3. If you have a stdio device, run 'nios2-terminal' in a different shell."
echo "    4. Run 'make download-elf' from the application directory."
echo
echo "To debug the application:"
echo "    Import the project into Nios II IDE.  Refer to Nios II IDE Documentation for more information."
echo


exit 0
